// +build autogen,!windows

// Package dockerversion is auto-generated at build-time
package dockerversion

// Default build-time variable for library-import.
// This file is overridden on build with build-time informations.
const (
	ContainerdCommitID string = "aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1"
	RuncCommitID       string = "9df8b306d01f59d3a8029be411de015b7304dd8f"
	InitCommitID       string = "949e6facb77383876aeff8a6944dde66b3089574"
)

// AUTOGENERATED FILE; see /go/src/github.com/docker/docker/hack/make/.go-autogen
